
export const StoreActionBlacklist = [
  // REHYDRATE,
  'redux-form/ARRAY_INSERT',
  'redux-form/ARRAY_MOVE',
  'redux-form/ARRAY_POP',
  'redux-form/ARRAY_PUSH',
  'redux-form/ARRAY_REMOVE',
  'redux-form/ARRAY_REMOVE_ALL',
  'redux-form/ARRAY_SHIFT',
  'redux-form/ARRAY_SPLICE',
  'redux-form/ARRAY_UNSHIFT',
  'redux-form/ARRAY_SWAP',
  'redux-form/AUTOFILL',
  'redux-form/BLUR',
  'redux-form/CHANGE',
  'redux-form/DESTROY',
  'redux-form/FOCUS',
  'redux-form/INITIALIZE',
  'redux-form/REGISTER_FIELD',
  // 'redux-form/RESET',
  'redux-form/SET_SUBMIT_FAILED',
  // 'redux-form/SET_SUBMIT_SUCCEEDED',
  'redux-form/START_ASYNC_VALIDATION',
  'redux-form/START_SUBMIT',
  'redux-form/STOP_ASYNC_VALIDATION',
  'redux-form/STOP_SUBMIT',
  'redux-form/TOUCH',
  'redux-form/UNREGISTER_FIELD',
  'redux-form/UNTOUCH',
  'redux-form/UPDATE_SYNC_ERRORS',
  'redux-form/UPDATE_SYNC_WARNINGS',
  'SET_SOCKET_CONNECTING'
];
