import { offlineActionTypes } from 'react-native-offline';
import coreTypes from 'rbv-core/actionTypes';

export const offline = offlineActionTypes;
export const _global = {
  DATA_VERSION_CHANGE: 'DATA_VERSION_CHANGE',
  KEYSTONE: '@@API/KEYSTONE',
  RESET_TRAINING_DATA: 'RESET_TRAINING_DATA',
  RESET_USER_DATA: 'RESET_USER_DATA',
  SIGN_OUT: 'SIGN_OUT',
  SYNC: '@@API/SYNC'
};



export default {
/** #### ACCOUNT #### **/
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  MODIFY_USER_ACCOUNT: 'MODIFY_USER_ACCOUNT',
  SET_AUTH_STATUS: 'SET_AUTH_STATUS',
  USER_IS_AUTHENTICATING: 'USER_IS_AUTHENTICATING',
  USER_AUTH_ATTEMPT: 'USER_AUTH_ATTEMPT',
  REFRESH_USER: 'REFRESH_USER',
  GET_STATIC_DATA: 'GET_STATIC_DATA',
  GET_USER_CUSTOM_DATA: 'GET_USER_CUSTOM_DATA',
  MODIFY_ATHLETE_PROFILE: 'MODIFY_ATHLETE_PROFILE',
  MODIFY_APP_CONFIG: 'MODIFY_APP_CONFIG',
  SET_ONBOARDING_STAGE: 'SET_ONBOARDING_STAGE',
  UPDATE_APP_DATA_VERSION: 'UPDATE_APP_DATA_VERSION',
  RESET_DATA_VERSION_CHANGE: 'RESET_DATA_VERSION_CHANGE',
  /* #################### */

  /** #### ASSESSMENTS #### **/
  GET_ASSESSMENTS: 'GET_ASSESSMENTS',
  /* #################### */

  /** #### DAILY LOGS #### **/
  GET_DAILY_LOGS: 'GET_DAILY_LOGS',
  SET_CURRENT_DAILY_LOG: 'SET_CURRENT_DAILY_LOG',
  SET_LOADING_STATUS: 'SET_LOADING_STATUS',
  /* #################### */

  /** #### DRAWER #### **/
  SET_DRAWER_STATE: 'SET_DRAWER_STATE',
  /* #################### */

  /** #### FITNESS TESTS #### **/
  GET_BEEP_TESTS: 'GET_BEEP_TESTS',
  GET_PREV_BEEP_TEST: 'GET_PREV_BEEP_TEST',
  SET_CURRENT_BEEP_TEST: 'SET_CURRENT_BEEP_TEST',
  RESET_CURRENT_BEEP_TEST: 'RESET_CURRENT_BEEP_TEST',
  /* #################### */

  /** #### INVITATIONS #### **/
  GET_INVITATIONS: 'GET_INVITATIONS',
  /* #################### */

  /** #### INJURIES #### **/
  GET_INJURIES: 'GET_INJURIES',
  SET_EDITING_INJURY: 'SET_EDITING_INJURY',
  /* #################### */


  /** #### MATCHES #### **/
  GET_MATCHES: 'GET_MATCHES',
  SET_EDITING_MATCH: 'SET_EDITING_MATCH',
  /* #################### */


  /** #### SETTINGS #### **/
  SET_SETTINGS_EDITING_STATUS: 'SET_SETTINGS_EDITING_STATUS',
  /* #################### */


  /** #### STRENTH TEST #### **/
  GET_PREV_STRENGTH_TEST: 'GET_PREV_STRENGTH_TEST',
  GET_COMPLETED_STRENGTH_TESTS: 'GET_COMPLETED_STRENGTH_TESTS',
  GET_CURRENT_STRENGTH_TEST: 'GET_CURRENT_STRENGTH_TEST',
  GET_AVAILABLE_STRENGTH_TEST_ACTIVITIES: 'GET_AVAILABLE_STRENGTH_TEST_ACTIVITIES',
  MODIFY_ACTIVE_STRENGTH_TEST_ACTIVITY_MODEL: 'MODIFY_ACTIVE_STRENGTH_TEST_ACTIVITY_MODEL',
  ADD_COMPLETED_STRENGTH_TEST_ACTIVITY: 'ADD_COMPLETED_STRENGTH_TEST_ACTIVITY',
  UPDATE_COMPLETED_STRENGTH_TEST_ACTIVITY: 'UPDATE_COMPLETED_STRENGTH_TEST_ACTIVITY',
  COMPILE_STRENGTH_TEST_ACTIVITIES: 'COMPILE_STRENGTH_TEST_ACTIVITIES',
  SET_CURRENT_STRENGTH_TEST: 'SET_CURRENT_STRENGTH_TEST',
  SET_FIRST_TEST_FLAG: 'SET_FIRST_TEST_FLAG',
  NAVIGATE_ACTIVITY: 'NAVIGATE_ACTIVITY',
  /* #################### */


  /** #### SUBSCRIPTION #### **/
  GET_STRIPE_ACCOUNT: 'GET_STRIPE_ACCOUNT',
  GET_SUBSCRIPTION_INDIVIDUAL: 'GET_SUBSCRIPTION_INDIVIDUAL',
  GET_SUBSCRIPTION_GROUP: 'GET_SUBSCRIPTION_GROUP',
  GET_INVOICES: 'GET_INVOICES',
  /* #################### */


  /** #### TEAM #### **/
  REFRESH_FEED: 'REFRESH_FEED',
  /* #################### */


  /** #### TRAINING #### **/
  GET_DEFAULT_TRAINING_PLAN: 'GET_DEFAULT_TRAINING_PLAN',
  GET_LATEST_TRAINING_PLAN: 'GET_LATEST_TRAINING_PLAN',
  GET_TRAINING_PLAN_TEMPLATE: 'GET_TRAINING_PLAN_TEMPLATE',
  PROCESS_TRAINING_PLAN: 'PROCESS_TRAINING_PLAN',
  UPDATE_CURRENT_TRAINING_PLAN: 'UPDATE_CURRENT_TRAINING_PLAN',
  SET_CURRENT_TRAINING_PLAN_ID: 'SET_CURRENT_TRAINING_PLAN_ID',

  // weekly routine
  SET_CURRENT_WEEKLY_ROUTINE: 'SET_CURRENT_WEEKLY_ROUTINE',
  SET_CURRENT_WEEKLY_ROUTINE_TEMPLATE: 'SET_CURRENT_WEEKLY_ROUTINE_TEMPLATE',
  GET_CURRENT_PLAN_WEEKLY_ROUTINES: 'GET_CURRENT_PLAN_WEEKLY_ROUTINES',

  // workouts
  SELECT_WORKOUT_SEGMENT: 'SELECT_WORKOUT_SEGMENT',
  CREATE_WORKOUT: 'CREATE_WORKOUT',
  SET_CURRENT_WORKOUT: 'SET_CURRENT_WORKOUT',
  SET_CURRENT_WORKOUT_TEMPLATE: 'SET_CURRENT_WORKOUT_TEMPLATE',
  SET_DAY: 'SET_DAY',
  SET_LATEST_WORKOUTS: 'SET_LATEST_WORKOUTS',
  SET_SELECTED_ID: 'SET_SELECTED_ID',
  UPDATE_CURRENT_WORKOUT: 'UPDATE_CURRENT_WORKOUT',

  // activity
  MODIFY_CURRENT_ACTIVITY: 'MODIFY_CURRENT_ACTIVITY',
  SET_RECENT_ACTIVITIES: 'SET_RECENT_ACTIVITIES',
  SET_CURRENT_ACTIVITY: 'SET_CURRENT_ACTIVITY',
  SET_CURRENT_ACTIVITY_INDEX: 'SET_CURRENT_ACTIVITY_INDEX',
  SET_CURRENT_ACTIVITY_TEMPLATE: 'SET_CURRENT_ACTIVITY_TEMPLATE',
  SET_CURRENT_SET: 'SET_CURRENT_SET',
  UPDATE_CURRENT_ACTIVITY: 'UPDATE_CURRENT_ACTIVITY',
  UPDATE_CURRENT_SET: 'UPDATE_CURRENT_SET',
  REPLACE_ACTIVITY_IN_WORKOUT: 'REPLACE_ACTIVITY_IN_WORKOUT',

  // process activity
  QUEUE_ACTIVITY: 'QUEUE_ACTIVITY',
  SELECT_ENQUEUED_ACTIVITY: 'SELECT_ENQUEUED_ACTIVITY',
  ADD_PROCESSED_ACTIVITY: 'ADD_PROCESSED_ACTIVITY',

  // prep activity
  REPLACE_ACTIVITY_IN_QUEUE: 'REPLACE_ACTIVITY_IN_QUEUE',
  SET_QUEUE_FOR_WORKOUT: 'SET_QUEUE_FOR_WORKOUT',
  SET_CARDIO_SELECTIONS: 'SET_CARDIO_SELECTIONS',
  /* #################### */

  /* SOCKET */
  SET_SOCKET_CONNECTING: 'SET_SOCKET_CONNECTING',
  /* #################### */

  /* MESSAGES & FEEDS */
  GET_ACCOUNT: '@@RTS/GET_ACCOUNT',
  DELETE_FEED: '@@RTS/DELETE_FEED', // also deletes messages!
  GET_FEEDS: '@@RTS/GET_FEEDS',
  SET_SELECTED_FEED: '@@RTS/SET_SELECTED_FEED',
  NEW_FEED: '@@RTS/NEW_FEED',
  LEAVE_FEED: '@@RTS/LEAVE_FEED',
  GET_MESSAGES: '@@RTS/GET_MESSAGES',
  UPDATE_FEED_MESSAGES: '@@RTS/UPDATE_FEED_MESSAGES',
  SET_NEW_MESSAGE: '@@RTS/SET_NEW_MESSASGE',
  DELETE_MESSAGE: '@@RTS/DELETE_MESSAGE',
  /* #################### */

  ...coreTypes
};
